# Generated by Django 6.1.1 on 2026-09-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('referente_padrao', models.CharField(default='Mensalidade', max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_mes', models.PositiveSmallIntegerField()),
                ('competencia_ano', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referente', models.CharField(max_length=150)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('gerado', 'Gerado')], default='pendente', max_length=20)),
                ('impresso', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='app.cliente')),
            ],
            options={
                'db_table': 'recibos',
                'ordering': ['-competencia_ano', '-competencia_mes'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'competencia_mes', 'competencia_ano'), name='uq_recibo_competencia')],
            },
        ),
    ]
