# Generated by Django 5.2.6 on 2026-09-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
